### ISSUE TITLE
ClassifierDLModel fails to load the pre-trained model file tfhub_use_en_2.4.0_2.4

### ISSUE THREAD

**Issue by fxu36** [JohnSnowLabs/spark-nlp#1043]
In Spark local environment on Windows 10,  I have a daemon process to run ClassifierDLModel::load between spark session start and stop.  ClassifierDLModel  works for the first time, then fails in SparkContext::assertNotStopped.  
## Expected Behavior

ClassifierDLModel ::load should be able to rerun after spark session stop in spark local mode on Windows. 
## Current Behavior

ClassifierDLModel ::load fails for second time with exception,

Exception in thread "main" java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
com.ddc.model.test.ClassifierTest$.test2(ClassifierTest.scala:28)
com.ddc.model.test.ClassifierTest$.main(ClassifierTest.scala:52)
com.ddc.model.test.ClassifierTest.main(ClassifierTest.scala)

The currently active SparkContext was created at:

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
com.ddc.model.test.ClassifierTest$.test2(ClassifierTest.scala:28)
com.ddc.model.test.ClassifierTest$.main(ClassifierTest.scala:53)
com.ddc.model.test.ClassifierTest.main(ClassifierTest.scala)
         
	at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:100)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1486)
	at com.johnsnowlabs.nlp.serialization.Feature$$anonfun$setValue$1.apply(Feature.scala:86)
	at com.johnsnowlabs.nlp.serialization.Feature$$anonfun$setValue$1.apply(Feature.scala:86)
	at scala.Option.map(Option.scala:146)
	at com.johnsnowlabs.nlp.serialization.Feature.setValue(Feature.scala:86)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:16)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:14)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:14)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at org.apache.spark.ml.util.MLReadable$class.load(ReadWrite.scala:380)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ClassifierDLModel$.load(ClassifierDLModel.scala:198)
	at com.ddc.model.test.ClassifierTest$.test2(ClassifierTest.scala:46)
	at com.ddc.model.test.ClassifierTest$.main(ClassifierTest.scala:53)
	at com.ddc.model.test.ClassifierTest.main(ClassifierTest.scala)

## Possible Solution

The member variable spark is cached in ResourceHelper, not sure if it's the cause.

lazy val spark: SparkSession = getActiveSparkSession

## Steps to Reproduce

import com.johnsnowlabs.nlp.annotator.ClassifierDLModel
import org.apache.spark.sql.SparkSession
object ClassifierTest {
    def test(): Unit = {
        val spark = SparkSession.builder
                .master("local[*]")
                .appName("classifier")
                .getOrCreate();
        val model = ClassifierDLModel.load("file:///C:\\work\\data\\model\\classifierdl_use_trec6_en_2.5.0_2.4");
        spark.stop();
    }
    def main(args: Array[String]): Unit = {
        test;
        test;
    }
}
## Context

It's a blocker, I have to create a new process for every run. 

## Your Environment

* Spark NLP version: 2.5
* Apache NLP version:
* Java version (java -version): 1.8
* Setup and installation (Pypi, Conda, Maven, etc.): 
* Operating System and version: Windows 10
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,
Just to be sure we use the same setup, where and how you run this code? If it's spark-submit then it closes the session when it's done. If it's inside IntelliJ the same thing happens. If the application is over there is no need to close the session and if it's still running you are not supposed to close it since you reuse it.

Just to be sure the concept behind closing the session and then create another one to close it again in the same application. (This may not be only for ClassifierDL and all the other annotators can have this behavior, I'll test this as soon as I understand where and how I should run this)

**Comment by fxu36** [comment]
I updated the sample code above to clarify the test is done in Scala application not spark-submit.
Our real application is a daemon/service to execute plugins submitted by end user, and the plugins are executed in the same daemon/service process . Some plugins are written in Spark MLlib enclosed in session start and stop because different ML job could run in local or cluster based on workload. Spark context stop and start are needed in the daemon/service because only one Spark context is allowed  by default.
Spark MLlib is good but only provides basic ML, and SparkNLP has a lot state of the art stuff we are interested in, however it breaks our current application  logic during evaluation.
I wonder if SparkNLP could provide API to update the spark session cached inside, so we could work around the problem.  Thansk!

**Comment by maziyarpanahi** [comment]
Thanks for the code snippet and the explanation. So if I understood correctly:

- The application is a Scala microservice that creates a SparkSession and once it's done it closes it for the next user's request? (like a queue to have always one SparkSession)
- My last question is where do you test this code? In the IntelliJ, I am not able to reproduce this. How and where do you run this code that resulted in that error?

NOTE: Spark NLP doesn't really interfere with SparkSession, actually without it doesn't work at all. It requires SparkSession to be created before so the Session has Spark NLP functions. In SparkSession already started by the user, in a few places it will reuse the current/existing SparkSession. For instance `getActiveSparkSession` is for our tests to create SparkSession in Travis or spark.read in some of the annotators but it will always reuse the existing SparkSession since in that point SparkSession must exist.

But I'd like to test this myself so if you can share your development environment so I can execute that code to be sure I would appreciate it.

**Comment by fxu36** [comment]
I run the test code in IntelliJ, and the model file is downloaded from your website at https://github.com/JohnSnowLabs/spark-nlp-models#english---pipelines. I'd change "file:///C:\work\data\model\classifierdl_use_trec6_en_2.5.0_2.4" to the place with the pre-trained model file.

**Comment by fxu36** [comment]
Are you able to reproduce the behavior, and what else should I provide? Thanks.
