### ISSUE TITLE
Unable to save ner_dl model to s3

### ISSUE THREAD

**Issue by mlocutus** [JohnSnowLabs/spark-nlp#1095]
## Description
after training a custom NER model, unable to upload it to s3.  the following error occurs:

```
ner_model.write.save("s3a://some_path_to/model/location/custom_ner_model_3")
org.apache.hadoop.fs.FileAlreadyExistsException: s3a://some_path_to/model/location/custom_ner_model_3/stages/0_NerDLModel_48ede697200a exists and is not a file
  at org.apache.hadoop.fs.s3a.S3AFileSystem.innerCopyFromLocalFile(S3AFileSystem.java:2395)
  at org.apache.hadoop.fs.s3a.S3AFileSystem.copyFromLocalFile(S3AFileSystem.java:2353)
```

adding `.overwrite()` doesn't solve the problem. same error occurs.

## Expected Behavior
the model files should be uploaded to s3

## Current Behavior
some files are successfully copied but not all

## Steps to Reproduce
1. train a custom NerDL model.  follow the notebook steps provided in the NLP Workshop tutorial
2. use ner_model.write.save to save the model to s3
3.
4.

## Your Environment

* Spark NLP version: 2.4.7
* Apache NLP version:
* Java version (java -version):
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version: linux
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
This issue seems to be between the fileSystem (S3) in Hadoop and Apache Spark. Could you please set the following config to true and try again:

```
spark.hadoop.orc.overwrite.output.file=true
```

**Comment by mlocutus** [comment]
thanks for the idea!  I tried this, but still got the same error:

```

scala> spark.sparkContext.hadoopConfiguration.set("orc.overwrite.output.file","true")
```


```
scala> ner_model.write.overwrite().save("s3a://path_to_s3/location/ner-training/4/custom_ner_model")
org.apache.hadoop.fs.FileAlreadyExistsException: s3a://path_to_s3/location/ner-training/4/custom_ner_model/stages/0_NerDLModel_b10cf8a3002b exists and is not a file
  at org.apache.hadoop.fs.s3a.S3AFileSystem.innerCopyFromLocalFile(S3AFileSystem.java:2395)
  at org.apache.hadoop.fs.s3a.S3AFileSystem.copyFromLocalFile(S3AFileSystem.java:2353)
  at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:2335)
  at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:2298)
  at com.johnsnowlabs.ml.tensorflow.WriteTensorflowModel$class.writeTensorflowModel(TensorflowSerializeModel.scala:37)
  at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel.writeTensorflowModel(NerDLModel.scala:24)
  at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel.onWrite(NerDLModel.scala:209)
  at com.johnsnowlabs.nlp.ParamsAndFeaturesWritable$$anonfun$write$1.apply(ParamsAndFeaturesWritable.scala:31)
  at com.johnsnowlabs.nlp.ParamsAndFeaturesWritable$$anonfun$write$1.apply(ParamsAndFeaturesWritable.scala:31)
  at com.johnsnowlabs.nlp.FeaturesWriter.saveImpl(ParamsAndFeaturesWritable.scala:18)
  at org.apache.spark.ml.util.MLWriter.save(ReadWrite.scala:180)
  at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$saveImpl$1.apply(Pipeline.scala:254)
  at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$saveImpl$1.apply(Pipeline.scala:253)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.apache.spark.ml.Pipeline$SharedReadWrite$.saveImpl(Pipeline.scala:253)
  at org.apache.spark.ml.PipelineModel$PipelineModelWriter.saveImpl(Pipeline.scala:338)
  at org.apache.spark.ml.util.MLWriter.save(ReadWrite.scala:180)
  ... 51 elided

```

**Comment by maziyarpanahi** [comment]
I've read on Databricks this happens from time to time between Apache Spark and S3. One of the workarounds was to clean up the path. Would it be possible to entirely remove `s3a://path_to_s3/location/ner-training/4/custom_ner_model/` and try again? And if that failed to choose another path?

Some resources regarding this issue between Apache Spark and S3 (unfortunately it is out of our hand in Spark NLP):
- https://forums.databricks.com/questions/1489/why-do-i-get-javaioioexception-file-already-exists.html
- https://stackoverflow.com/questions/50868123/s3afilesystem-filealreadyexistsexception-when-prefix-is-a-file-and-part-of-a-d
- https://stackoverflow.com/questions/57471781/spark-filealreadyexistsexception-on-stage-failure
- https://stackoverflow.com/questions/49102292/file-already-exists-error-writing-new-files-from-dataframe

Also, I see it is talking about stages, perhaps you are saving the entire pipeline rather than saving just NerDLModel. It's not really related to the error, but if you provide your code for training I can tell you how to save an estimator from a pipeline separately so you can load it in another pipeline.

**Comment by mlocutus** [comment]
here's the code used for training and saving the model:

```
val bert_annotator = BertEmbeddings.pretrained(embeddingsName, "en").setInputCols("sentence", "token").setOutputCol("bert").setCaseSensitive(true)

val training_data = CoNLL().readDataset(spark, "s3a://path_to_s3/training/training.iob2")
val bert_annotated_training_data = bert_annotator.transform(training_data)

val conll_test_data = CoNLL().readDataset(spark, "s3a://path_to_s3/training/test.iob2")
val test_data = bert_annotator.transform(conll_test_data)
test_data.write.mode("overwrite").parquet("testData_withEmbeds.parquet")


val nerTagger = new NerDLApproach()
    .setInputCols("sentence", "token", "bert")
    .setLabelColumn("label")
    .setOutputCol("ner")
    .setMaxEpochs(epochs)
    .setLr(0.001f)
    .setPo(0.005f)
    .setBatchSize(32)
    .setRandomSeed(0)
    .setVerbose(Verbose.Epochs)
    .setValidationSplit(0.2f)
    .setEvaluationLogExtended(true)
    .setEnableOutputLogs(true)
    .setIncludeConfidence(true)
    .setTestDataset("testData_withEmbeds.parquet")
    .setOutputLogsPath("/data/log/ner-training-3-output.log")

val trainingPipeline = new Pipeline().setStages(Array(nerTagger))

val ner_model = trainingPipeline.fit(bert_annotated_training_data)

ner_model.write.overwrite().save("s3a://path_to_s3/location/ner-training/4/custom_ner_model")

```

it's loosely based on the example here (which has been really helpful!) https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/blogposts/3.NER_with_BERT.ipynb

Happy to refactor it if there's a better way to save (and then subsequently re-load) the model.

**Comment by maziyarpanahi** [comment]
That is correct to save it as a whole Pipeline, and once you load it you will have all the stages back. But since you only have 1 stage in the Pipeline, then there is no need to have a pipeline:

```scala

val nerTagger = new NerDLApproach()
    .setInputCols("sentence", "token", "bert")
    .setLabelColumn("label")
    .setOutputCol("ner")
    .setMaxEpochs(epochs)
    .setLr(0.001f)
    .setPo(0.005f)
    .setBatchSize(32)
    .setRandomSeed(0)
    .setVerbose(Verbose.Epochs)
    .setValidationSplit(0.2f)
    .setEvaluationLogExtended(true)
    .setEnableOutputLogs(true)
    .setIncludeConfidence(true)
    .setTestDataset("testData_withEmbeds.parquet")
    .setOutputLogsPath("/data/log/ner-training-3-output.log")

val ner_model = nerTagger.fit(bert_annotated_training_data)

ner_model.write.overwrite().save("s3a://path_to_s3/location/ner-training/4/custom_ner_model")

```

Now you have NerDLModel saved, you can load it inside a pipeline as follow:

``scala

val documentAssembler = new DocumentAssembler()
      .setInputCol("text")
      .setOutputCol("document")

    val sentence = new SentenceDetector()
      .setInputCols("document")
      .setOutputCol("sentence")

    val tokenizer = new Tokenizer()
      .setInputCols(Array("sentence"))
      .setOutputCol("token")
     
//embeddingsName must be the exact same embeddngs used to train the NerDL
// it stores the reference to make this sure
  val bert_annotator = BertEmbeddings.pretrained(embeddingsName, "en").setInputCols("sentence", "token").setOutputCol("bert").setCaseSensitive(true)

    val ner = NerDLModel.load("PATH to saved NerDLModel")
      .setInputCols("sentence", "token", "embeddings")
      .setOutputCol("ner")

    val nerConverter = new NerConverter()
      .setInputCols("sentence", "token", "ner")
      .setOutputCol("entities")

    val pipeline = new Pipeline()
      .setStages(Array(
        documentAssembler,
        sentence,
        tokenizer,
        bert_annotator,
        ner,
        nerConverter
      ))

```

Then you can .fit() and .transform this pipeline which will use your custom NerDLModel. (again, this is not about the issue you are facing, unfortunately it is between S3, Hadoop, and Apache Spark)
