### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.ml.tensorflow.sentencepiece.SentencePieceJNI

### ISSUE THREAD

**Issue by jdbotha** [JohnSnowLabs/spark-nlp#1099]
When utilizing xlnet_base or albert embeddings in pretrained pipeline, error of missing class thrown during initialization of the embeddings in PySpark.

## Current Behavior
Fails on collection: result.select("xlnet.embeddings").show(5, False)

py4j.protocol.Py4JJavaError: An error occurred while calling o607.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 25.0 failed 4 times, most recent failure: Lost task 0.3 in stage 25.0 (..., executor # ): java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.ml.tensorflow.sentencepiece.SentencePieceJNI

## Steps to Reproduce
xlnet = (
    XlnetEmbeddings.pretrained().setInputCols("sentence", "token").setOutputCol("xlnet")
)

pipeline = Pipeline().setStages([explain_pipeline_model, xlnet])

pipeline = RecursivePipeline(stages=[explain_pipeline_model, xlnet])

result = pipeline.fit(data.limit(10)).transform(data.limit(10))

# Check schema
result.printSchema()
result.select("xlnet.embeddings").show(5, False)

## Context
This prevents albert/xlnet embeddings from being utilized for modelling purposes.

## Your Environment
Python 3.6.9
spark.jars.packages=com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:2.6.2

>>>sparknlp.version()
'2.6.2'

>>> spark.version
'2.4.0.7.1.2.0-96'

* Java version (java -version):
java version "1.8.0_231"

* Setup and installation (Pypi, Conda, Maven, etc.):
$ conda create -n sparknlp python=3.6.9 -y
$ conda activate sparknlp
$ pip install spark-nlp==2.6.2 pyspark==2.4.4

**Comment by maziyarpanahi** [comment]
Hi,
Could you please mention your OS for reproducibility?

**Comment by jdbotha** [comment]
Hello, I believe its Ubuntu 18.04.3 LTS.

**Comment by maziyarpanahi** [comment]
Thanks, may I ask how you start your SparkSession?

**Comment by jdbotha** [comment]
Starting spark session via spark-defaults.conf:
spark.yarn.appMasterEnv.PYSPARK_PYTHON=./ENV/env/bin/python
spark.yarn.appMasterEnv.PYSPARK_DRIVER_PYTHON=./ENV/env/bin/python
spark.yarn.dist.archives=env.zip#ENV

spark.jars.packages=org.apache.kudu:kudu-spark2_2.11:1.10.0,com.microsoft.sqlserver:mssql-jdbc:7.2.2.jre8,com.johnsnowlabs.nlp:spark-nlp_2.11:2.6.2

spark.sql.codegen.wholeStage=false

## Set-up Spark session
spark = SparkSession.builder.appName("env").getOrCreate()
sc = spark.sparkContext

**Comment by jdbotha** [comment]
> Thanks, may I ask how you start your SparkSession?

Any update on this issue?

**Comment by maziyarpanahi** [comment]
Unfortunately I cannot reproduce this. The template is not correctly filled and has some mismatched info.
It seems it's a cluster since you use yarn config but you never mentioned which cluster. You mentioned using spark.jars.packages=com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:2.6.2 but then mentioned installing pyspark=2.4.4. A package for apache spark 2.3.x is compatible for the same major version.

Locally I don't see any issue on Ubuntu 18 using the correct versions which for pyspark 2.4.4 is the default versions without adding 23.

If the error persists please create another issue but this time full template with full info as we need to follow the exact same Environment to reproduce and help.
