### ISSUE TITLE
ELMo Embeddings -> Document Feature Vector

### ISSUE THREAD

**Issue by ajhepburn** [JohnSnowLabs/spark-nlp#1132]
https://nlp.johnsnowlabs.com/docs/en/annotators#elmoembeddings

**ElmoEmbeddings**

Not entirely sure how to get a fixed-length, per-document feature vector out from my pretrained ELMo pipeline. Am I missing some vital step here? I could be wrong, but I recall built-in functionality which achieved this? I tried using `SentenceEmbeddings` but don't think that's what I'm looking for. Am I just better averaging across word vectors manually?

```
    def elmo_tokenize(df: DataFrame):
        document_assembler = (DocumentAssembler()
                              .setInputCol('text_type')
                              .setOutputCol('doc'))
        tokenizer = (Tokenizer()
                     .setInputCols('doc')
                     .setOutputCol('token'))
        
        elmo = (ElmoEmbeddings()
                .load('/nfs/models/pretrain/elmo')
                .setInputCols(['doc', 'token'])
                .setOutputCol('elmo')
                .setPoolingLayer('word_emb'))
        
        embeddings_finisher = (EmbeddingsFinisher()
            .setInputCols('elmo')
            .setOutputCols('elmo_vectors')
            .setOutputAsVector(True))

        pipe = Pipeline(stages=[document_assembler, 
                                tokenizer,
                                elmo,
                                embed_finisher,
                               ])
        return pipe.fit(df).transform(df)
```

Inputs are simply row-by-row strings.

**Comment by maziyarpanahi** [comment]
Hi,

Could you please elaborate more? Fixed length could mean couple of things so I am not sure which one is the subject here. (Describing the use case also helps)

**Comment by C-K-Loan** [comment]
Hi @ajhepburn 
 it seems what you want to use would be SentenceEmbeddings, it converts any WordEmbeddings to Sentence Embeddings.
This will resulting Sentence Embeddings will all be the same length/shape/dimension

https://nlp.johnsnowlabs.com/docs/en/annotators#sentenceembeddings .


Just using Elmo is a one to Many mapping between Document and Vectors.  Since each document consists of many Words.

Using SentenceEmbeddings one to one mapping between Document and Vectors. Since each Vector is an accumulation of all Word Vectors into a fixed dimension.

Hope this helps to clear everything up
