### ISSUE TITLE
Retraining with new data samples

### ISSUE THREAD

**Issue by vlreinier** [JohnSnowLabs/spark-nlp#1278]
**Describe the solution you'd like**

Is it currently possible to retrain a NerDLApproach model with data new samples (instead of retraining complete dataset + new samples)?

Thanks in advance!

**Comment by maziyarpanahi** [comment]
Hi,

Unfortunately, that is not possible at the moment. We don't have any immediate plan for this as it requires lots of testings for proven practicality.

**Comment by vlreinier** [comment]
Ok thanks for your quick response :)

**Comment by maziyarpanahi** [comment]
Since this question comes up every once in a while, to understand the use cases and possibilities, other approaches, and existing features, etc. I would like to turn this into a discussion. This allows other users to chime in and continue the conversation so when we do plan it we know what's required and how it will be used.
