### ISSUE TITLE
migration to scala 2.13

### ISSUE THREAD

**Issue by LucaPifferettiPrivate** [JohnSnowLabs/spark-nlp#13129]
**Is your feature request related to a problem? Please describe.**
I'm trying to develop a ner model to find out PER inside texts, but i'm bound to scala 2.13 version.

**Describe the solution you'd like**
I would like to understand if there is some development of spark-nlp compatible with scala 2.13.

**Describe alternatives you've considered**
I have an alternative solution: take the pieces of code required to find person entities inside texts and make it available in scala 2.13.

**Comment by maziyarpanahi** [comment]
Hi,

At this point Spark NLP is not compatible with Scala 2.13.x. We tried to do this migration, but we have a huge blocker when it comes to the serialization of our existing models/pipelines (more than 11k!). This means we have to re-save/re-upload all of them because Scala is not stable and safe when it goes from one major version to another.

We have postponed this until we see Apache Spark on Scala 3.x which makes the all of these efforts worth doing. Hopefully, Scala 3.x is more stable between major releases and we can avoid re-saving all of our models in the future.

That's said, you can have a look at how we tried to make Spark NLP compatible with Scala 2.13, pick the latest release, replicate the same changes, and try to train a NER model yourself (or you can have another project in Scala 2.12.x behind APIs and call those from your project on Scala 2.13):
- community efforts: https://github.com/JohnSnowLabs/spark-nlp/pull/6464
- official efforts: https://github.com/JohnSnowLabs/spark-nlp/pull/6833
