### ISSUE TITLE
NerDLApproach is slow at inference

### ISSUE THREAD

**Issue by Tasos1** [JohnSnowLabs/spark-nlp#13602]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

Maziyar Panahi

### What are you working on?

I've trained a NER model on custom data using NerDLApproach. I'm finding that when using the model for inference it is too slow for my requirements and I want to understand if this is the expected behaviour and if there are ways it can be improved. 

**Model Info:**
- Embeddings : "small_bert_L2_768"
- Number of Tags: 428
- Number of Characters: 60

**Inference Data Info:**
- 100,000 documents
- average document length is 800 characters

**Inference Process and Timings:**
- Pre-processing (documentAssembler -->sentenceDL-->tokenizer-->Bert): ~30mins
- Saved output to hive database table
- Loaded data from table
- Inference (NerDLModel-->NerConverter): ~40mins

**Infrastructure:**
- Databricks Runtime: 12.1 ML (includes Apache Spark 3.3.1, GPU, Scala 2.12)
- GPU: Standard_NC4as_T4_v3 (1 Driver (28GB) + 2 workers (28GB each) ) 

### Current Behavior

Around 40 minutes to predict 100K examples (pre-processing excluded)

### Expected Behavior

Not expected but ideally prediction should take < 1-2 minutes (pre-processing excluded)

### Steps To Reproduce

Unfortunately I cannot share the code

### Spark NLP version and Apache Spark

Spark NLP version: 4.3.1
Spark version: 3.3.1

### Type of Spark Application

Python Appliation

**Comment by maziyarpanahi** [comment]
- It's impossible to say this should take 1-2 minutes! Even with a small BERT the NER is not a simple pre-processing task
- Since you are using small BERT, then there is no need for using GPU. switching to CPU with more cores will give you more parallelism and it will finish faster
- Also, it's impossible to debug this here since we don't have the dataset (no way to reproduce this)

Everything listed here is discussed in this Webinar, I highly recommend watching it. (it has CPU vs. GPU, when not to use GPUs, correctly partitioning to get the most out of a Cluster)
https://www.johnsnowlabs.com/watch-webinar-speed-optimization-benchmarks-in-spark-nlp-3-making-the-most-of-modern-hardware/

**Comment by Tasos1** [comment]
Thank you for the quick response and the tips!
