### ISSUE TITLE
ERROR Physical memory usage is too high

### ISSUE THREAD

**Issue by sudhirkr** [JohnSnowLabs/spark-nlp#13843]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

-  Trained customer NER model. 
- Created spark context 
- Loading it using NerDLModel.load()
- Closing sparksession

### Current Behavior

After closing spark session, expected that the used RAM would be freed up, but it is not.

### Expected Behavior

Expected behavior that once the spark session is closed, RAM is freed. Any number of call to NerDLModel.load() followed by closing of spark session should not exhaust RAM.

### Steps To Reproduce

1. Create spark session
2. Load the NER model with NerDLModel.load() trained with embeddings bert_base_uncased
3. Close the spark session
4. Wait for few minutes. I waited for 20 minutes.

### Spark NLP version and Apache Spark

sparkVersion = "2.4.5"
hadoopVersion = "2.7.7"
sparkNlpVersion = "3.0.0"
tensorflowMklVersion = "0.3.3"

### Type of Spark Application

Scala Application

### Java Version

 java -version openjdk version "1.8.0_362" OpenJDK Runtime Environment (build 1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09) OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

### Operating System and Version

Ubuntu and CentOS

**Comment by maziyarpanahi** [comment]
A few points here:

- We dropped the support for Apache Spark 2.x a long time ago, so whatever is going on on a very old version we cannot check
- You cannot close the SparkSession, once it's loaded it's there and you can Spark NLP. If by any chance you manage to kill it, then you cannot use Spark NLP since it requires the SparkSession to be active. (so this line saying `NerDLModel.load() after followed by closing of spark session` not possible)

The memory is 100% managed by JVM, it cleans when it cleans and releases the memory. It cannot be forced and it is the same for all the JVM based applications (Elasticsearch, Apache Spark, etc.)
