### ISSUE TITLE
Grammar extraction (chunking or phrase extraction)

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#157]
Hi,

Since there are two annotators already exist `PerceptronApproach ` and `RegexMatcher `, is it possible to have a new annotator (or function/feature) for grammar extraction or chunking? Stanford CoreNLP has some regex annotators to do this and I think it would be a great feature to have in spark-nlp:

Example for : 
```
[{pos:NN}|{pos:NNS}|{pos:JJ}]
```
Or just pure regex:
```
"(?:\\w+_JJ )+\\w+_(?:N[NP]".r
```
Where the result of POS is:
```
Linear_JJ discriminant_JJ analysis_NN LDA_NN is_VBZ a_DT generalization_NN of_IN Fishers_NNS linear_JJ discriminant_NN a_DT method_NN used_VBN
```

I appreciate any advice or help to do this by `spark-nlp` if it's already possible.
Thanks.

**Comment by saifjsl** [comment]
Thank you @maziyarpanahi for proposing this feature and with the example. Chunking is on our roadmap but still undefined priority or release date. 

Currently this would be possible with the RegexMatcher annotator, if you accordingly use a Finisher annotator with inputs targeting the token annotator and the POS annotator.

This would generate two array columns (one containing the POS tags and another one, the tokens). With some Spark manipulation, you should be able to zip these arrays, and convert them to text afterwards (with some unique delimiter)

With this result, you can build a new pipeline using a DocumentAssembler and a RegexMatcher in order to match those expressions you have.

Sounds a little bit of work but nothing very difficult

Best

**Comment by maziyarpanahi** [comment]
I think we can close this feature request as `Chunker()` annotator does exactly as I have wished for. 
Thank you 👍
