### ISSUE TITLE
Does spark nlp work with Apache ignite?

### ISSUE THREAD

**Issue by ga243** [JohnSnowLabs/spark-nlp#166]
I want to perform some ml task in application written in java and then some spark nlp task in python and / or scala applications. Is it possible to have the data shared between different applications written in different languages (one of which performs spark nlp processing) using Apache Ignite?

**Comment by showy** [comment]
@ga243 Sadly we currently don't have any specific APIs in the spark-nlp library (annotators and helpers) to connect to Ignite, so I guess you will need to retrieve the data using external libraries. :(

It would be interesting to plan support for ignite in the future @saifjsl

**Comment by maziyarpanahi** [comment]
`spark-nlp` is a native library on top of the Apache Spark ML. Apart from all the advantages of running `spark-nlp` natively in Spark, it also takes advantage of the Spark ecosystem. This means you get to do your ML/DL pipeline anywhere, for instance, Apache Ignite and use Spark to read/write the results. 

You can read any data from any source by using Spark which can come from another pipelines, then use `spark-nlp` to have NLP Pipeline, and the results can go back to any data source by using Spark for further processing/reporting/warehousing/etc. Using Apache Spark makes it easier to deal with all sort of platforms such as Elasticsearch, Cassandra, MongoDB, ignite, HBase, etc.

I believe, since you need to have Apache Spark to run `spark-nlp`, it's best to use Apache Spark to connect to those external sources instead of `spark-nlp` providing those external connectors.
