### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by MobinRanjbar** [JohnSnowLabs/spark-nlp#199]
Hi there,

I have a critical problem with NLP tools if they support other language like Persian/Farsi. Is SparkNLP support other language?

Thanks

**Comment by saifjsl** [comment]
Hi @MobinRanjbar 

Spark-NLP is currently language agnostic (except for the Stemmer) on occidental languages. None of our current contributors know about other language support, feel free to provide any feedback or contributions.

**Comment by saifjsl** [comment]
Closing this, not an issue or a specific feature request. Continue on Slack for questions.

**Comment by MobinRanjbar** [comment]
@saifjsl OK, but you tagged this as a Feature Request and you are saying this is not a feature request?!

**Comment by snape6666** [comment]
i would like to request german as one of the first languages ;)

**Comment by maziyarpanahi** [comment]
Hi @MobinRanjbar, @snape6666,

As you may have noticed, `spark-nlp` has many annotators to help users to construct their NLP Pipeline. Creating an entire NLP Pipeline for one language requires a good amount of dataset that is labeled correctly with high and acamdic quality to cover all the annotators (Lemma, POS, Sentiment, NER, etc.). Unfortunately, today this is only true and available for English and a few other mostly used languages while the others are just possible for one or two annotators without the possibility of being state of the art models with 97% accuracy. (that is why other NLP libraries and packages only support few languages)

That's being said, `spark-nlp` has been designed and developed the way to make the training process easy to encourage other users to train their own models. For instance, I have already trained some models for some annotators based on the data I could find for other languages. This soon will be available as `community models`.

I would like to also invite you and other users to help the community to track down high-quality datasets for training models by `spark-nlp`. Since users are native in those languages, it is much easier for them to find the datasets and share them with others.

Many thanks for your interest in using `spark-nlp` for other languages. 👍
