### ISSUE TITLE
Support for Offline/Air-Gaped Spark Clusters

### ISSUE THREAD

**Issue by thesuperzapper** [JohnSnowLabs/spark-nlp#208]
Is it currently possible to use pretrained models in offline Spark clusters, for example, submitting the trained model files along with the Spark job, because right now it seems as if there is no way to point to a local version of the pretrained models.

**Comment by saifjsl** [comment]
Hi @thesuperzapper sorry for the delay. This is a much better question for Slack, since here is more for issues. Please join so.

To close the issue answering shorty. Yes, if you are offline, you should save the pretrained() contents (usually in $HOME/cached_pretrained) and load them using e.g. PerceptronModel().load("path/to/folder"). 

pretrained() function is exclusively online, so it will always connect to our servers for metadata revision control. Use load() to manually read from disk.
