### ISSUE TITLE
Details of ClassifierDLApproach and SentimentDLApproach

### ISSUE THREAD

**Issue by sharockys** [JohnSnowLabs/spark-nlp#2116]
**Link to doc page in question (if any):**
https://nlp.johnsnowlabs.com/docs/en/annotators
**Name of the Spark NLP feature whose docs need improvement:**
#classifierdl-multi-class-text-classification
#sentimentdl-multi-class-sentiment-analysis-annotator
**What you think the docs should say:**

Hello, I am looking all over the doc and the source code to find out what's the exact architectures of these models, but I failed to find useful informations. Is that possible to add a few descriptions of these models, please? 
Thank you very much.

**Comment by maziyarpanahi** [comment]
Hi,
We should include the information regarding the DL architecture in the docs since they are built outside, but for now, they are in the header of each annotator: 
- https://nlp.johnsnowlabs.com/api/index.html#com.johnsnowlabs.nlp.annotators.classifier.dl.ClassifierDLApproach
- https://nlp.johnsnowlabs.com/api/index.html#com.johnsnowlabs.nlp.annotators.classifier.dl.MultiClassifierDLApproach

The `SentimentDL` reuses the same architecture designed for `ClassifierDL`.

**Comment by C-K-Loan** [comment]
I will get all the info available in our repos and update the docs accordingly within the next few days

**Comment by sharockys** [comment]
Thank you all for your quick response! 

It was good to know that they are the same model architecture behind. 


Have a nice day. 😃

**Comment by Rishab-Vanigotha** [comment]
ClassifierDLapproach is a deep neural network but what internally it uses to classify text? is it ANN or RNN or LSTM or GRU? how many hidden layers are there?
