### ISSUE TITLE
how much memory does it require to train the crf-ner model?

### ISSUE THREAD

**Issue by algoscale1** [JohnSnowLabs/spark-nlp#217]
I am trying to train the crf-ner model in Scala on a 16gb machine but getting java.lang.OutOfMemoryError. I am using the same data that are used in the below link.
https://github.com/JohnSnowLabs/spark-nlp/blob/1.5.4/python/example/crf-ner/ner.ipyn

How much memory does it need?
And do we have some examples for ner in scala?

**Comment by saifjsl** [comment]
Hello @algoscale1 , please join our Slack channel, it is more appropriate for these kind of questions than here.

To answer quickly here, NerCRF Is quite memory hungry because of the nature of its training dataset (one row per token). I want to work on it to improve it soon. I've heard of this problem with larger than 15MB CoNNL data already, also because it adds up with WordEmbeddings which are hungry.

For examples in Ner scala, take a look at this one:
https://github.com/JohnSnowLabs/spark-nlp/blob/master/example/src/NerDLPipeline.scala
