### ISSUE TITLE
End to end SBT project in Scala

### ISSUE THREAD

**Issue by baughmann** [JohnSnowLabs/spark-nlp#2221]
# Description
### Feature Request: Not a bug
Citing the fact that this library requires [out-of-date version of Scala and Spark](https://github.com/JohnSnowLabs/spark-nlp/issues/308), it would significantly help newcomers if there were a *complete* example project that included sample `pom.xml` and/or `build.sbt` files and the proper configuration needed.

Of course, this is not just an issue with this library, but is a core Spark issue. However, it would save a lot of time for newbies to Spark and this library if there were a read-to-go `build.sbt` file somewhere.

I'm currently sorting through this mess myself (downgrading from Scala 2.13 to 2.11 in order to use Spark), and would be happy to submit my `build.sbt` file and associated `docker-compose.yml` file once I figure it out, if we can find a good place to put it on this repo (or another one).

Please let me know what you guys think, and thanks for this awesome toolset!

## Steps to Reproduce

Not applicable

## Your Environment

Not applicable

**Comment by baughmann** [comment]
@maziyarpanahi You're definitely correct, this is not a problem with spark NLP alone, *kind-of*. The latest version of Spark supports Scala 2.12 which alleviates most of my dependency woes. 

But your suggestion is definitely the best way forward, and I will return once I have a working setup.

As far as real world examples (i.e., not using the Spark via command line, and not using Jupyter notebook), I've really been struggling to find any. I think I may have been using the incorrect search terms. Do you have any links to real-world examples?

BTW, thank you for your help thus far.

**Comment by maziyarpanahi** [comment]
You are very welcome, we do have lots of users using Fat JAR to submit their jobs on EMR, GCP, etc. It's true, we don't have many examples for them apart from that starter project I gave you. Most of the examples are to show how to use the library, especially in PySpark/Jupyter since it's easier to just run it immediately.

Also, you can easily change the Scala version to 2.12.13 and the Apache Spark version to 3.0.1 as we are doing it ourselves to start supporting Apache Spark 3.0.1, there are a few small issues in some models, but apart from that everything else is compatible. (Apache Spark 2.3.x and 2.4.x are being heavily used by our users and all the people in production, so we had to make sure we will support all 2.3, 2.4, and 3.0 on Scala 2.11 and Scala 2.12 since the other two versions won't go anywhere anytime soon.)

While you are making a PoC against Apache Spark alone to match your dependencies and see if you can shade some and whether there is an issue, I'll start adding more examples in that starter project with instructions as to how to package it and use it with spark-submit.

**Comment by baughmann** [comment]
It makes sense to focus on the get-started-right-away type of project setups, for sure. For experienced Spark users, It's probably the most beneficial. However, I do not fall into the "experienced user" category haha.

RE: 3.0.1, really? That's fantastic news! I had tried with 3.0.1 earlier but ran into some issues. Now that I have a slightly better handle on submitting an application,I will give it another try.

Do you think using something like [`sbt-cross`](https://github.com/lucidsoftware/sbt-cross) for a in a multi-module SBT project  would help?

**Comment by maziyarpanahi** [comment]
In your case using it I am not sure it would work. I am guessing you want to keep your project on Scala 2.13 while using Apache Spark (and other libraries relying on Spark) on 2.12. You can try, but I suspect lots of issues. The best is to pick a version of Apache Spark, maybe 2.4.x which is widely used with lots of tutorials/articles, and try to make it work in your setup. Once that is done, it's much easier to incorporate other dependencies.

**Comment by baughmann** [comment]
Thank you for your help, I will do some playing around when I can and get back to you here

**Comment by baughmann** [comment]
I've temporarily given up on using the MinIO Java client directly in lieu of using Spark's S3 capabilities (MinIO is S3 compliant). I've gotten it to work on my local dev cluster (`local[*]`) but not on my Docker cluster, even when assembling a fat JAR and submitting it with the job.

It might be a few days or a week or so before I have something. It seems I have *even more* to learn about dependency management on Spark clusters than I had realized...

**Comment by baughmann** [comment]
@maziyarpanahi I know this is off topic, so feel free to mark this comment accordingly. However, I would appreciate your input on [this question](https://softwareengineering.stackexchange.com/questions/421782/how-whether-to-include-apache-spark-in-my-architecture). I'm in the midst of this decision now and am unsure which route to take.

I've gotten it working, so far, with some of my external dependencies working. I have yet to integrate NLP, but want to settle that question before I go further.

**Comment by maziyarpanahi** [comment]
We have just made a public pre-release for Spark NLP `3.0.0-rc8`:
https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.0.0-rc8
