### ISSUE TITLE
SPARKNLP 3.0 jar file not having sparknlp

### ISSUE THREAD

**Issue by gourav-sg** [JohnSnowLabs/spark-nlp#2567]
## Description
when we try to import sparknlp in EMR 6.2.0 it says sparknlp does not exists

## Expected Behavior
it should say sparknlp exists. When I execute the `jar tf` script for older version the output is as follows:

```
jar tf spark-nlp-assembly-2.5.0.jar | egrep sparknlp
build/lib/sparknlp/
sparknlp/
build/lib/sparknlp/__init__.py
build/lib/sparknlp/annotation.py
build/lib/sparknlp/annotator.py
build/lib/sparknlp/base.py
build/lib/sparknlp/common.py
build/lib/sparknlp/embeddings.py
build/lib/sparknlp/functions.py
build/lib/sparknlp/internal.py
build/lib/sparknlp/pretrained.py
build/lib/sparknlp/storage.py
build/lib/sparknlp/training.py
build/lib/sparknlp/util.py
sparknlp/__init__.py
sparknlp/annotation.py
sparknlp/annotator.py
sparknlp/base.py
sparknlp/common.py
sparknlp/functions.py
sparknlp/internal.py
sparknlp/pretrained.py
sparknlp/training.py
sparknlp/util.py
```

## Current Behavior
`jar tf /usr/lib/spark/jars/spark-nlp-gpu-assembly-3.0.0.jar | egrep sparknlp` does not yield anything

## Possible Solution
there must have been some issue with the build process

## Steps to Reproduce
1. Go to https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.0.0 
2. scroll down and copy the jar file https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/jars/spark-nlp-assembly-3.0.0.jar and upload to your s3 location
3. modify bootstrap script so that the file is copied to the /usr/lib/spark/jars folder during EMR startup
4. start pyspark
5. import pyspark
Otherwise you can just execute the command:

```
jar tf /usr/lib/spark/jars/spark-nlp-gpu-assembly-3.0.0.jar | egrep sparknlp 
OR
jar tf spark-nlp-assembly-3.0.0.jar | egrep sparknlp
```
both the above commands do not yield anything. Please note that only spark-nlp-gpu-assembly-3.0.0.jar is there in the SPARK_HOME/jars folder, the other was just downloaded for checking. 

## Context

I was trying to run sparknlp in order to do NLP, and it does not help me start SPARKNLP anymore

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.0.0
* Apache NLP version `spark.version`:
* Java version `java -version`: 1.8.0
* Setup and installation (Pypi, Conda, Maven, etc.): fat jar
* Operating System and version: EMR 6.2.0
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

- Please follow the instruction for EMR to have Spark NLP for both Scala/Java and Python correctly setup. It's pretty simple and it has been tested on all the supported EMR versions with Spark NLP 3.0.0. (instead of spark.jars.packages you can use spark.jars to point to a Fat JAR, but the both is the same) https://github.com/JohnSnowLabs/spark-nlp#emr-cluster
- Please provide code, bootstrap, software configuration, and the full error. Looking inside the Fat JAR looking for something like `sparknlp` is not something we can rely on to reproduce this.

PS: those are Python APIs, I don't think they really belong inside the Fat JAR so probably they won't be included anymore since it will rely on the `pip install spark-nlp` PyPI package for those APIs. (as it is explained in the bootstrap.sh)
