### ISSUE TITLE
How can Spark NLP be used offline (behind a fire-wall)?

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#2780]
**Link to doc page in question (if any):**
I am trying to follow the Hello World example on the john snowlabs home page:
https://nlp.johnsnowlabs.com/

```Python
from sparknlp.base import *
from sparknlp.annotator import *              
from sparknlp.pretrained import PretrainedPipeline
import sparknlp
              
# Start Spark Session with Spark NLP
spark = sparknlp.start()
              
# Download a pre-trained pipeline 
pipeline = PretrainedPipeline('explain_document_dl', lang='en')

# Annotate your testing dataset
result = pipeline.annotate("The Mona Lisa is a 16th century oil painting created by Leonardo. It's held at the Louvre in Paris.")
              
# What's in the pipeline
list(result.keys())
Output: ['entities', 'stem', 'checked', 'lemma', 'document', 'pos', 'token', 'ner', 'embeddings', 'sentence']
              
# Check the results
result['entities']
Output: ['Mona Lisa', 'Leonardo', 'Louvre', 'Paris']
```

...but I cannot get past the pipeline statement because my environment is a closed and sealed off to the rest of the world.
![Unbenannt](https://user-images.githubusercontent.com/2129700/115414702-8debce00-a1f6-11eb-80fc-4e1a66d73d89.png)

So, I am wondering if there is a similar feature to NLTK that lets you:
1) download `nltk.download('stopwords')` and
2) install typical models locally (eg: in '/usr/share/nltk_data/'),
3) and then lets you use them from a local path (instead of downloading a model in an online scenario)

**Name of the Spark NLP feature whose docs need improvement:**
I could not find any Spark NLP version's doc that would help me in this regard, although, I'd be very much surprised if you have to be online to use Spark NLP with its models (sentence splitting etc).

**What you think the docs should say:**
If there is no documentation on the offline usage of Spark NLP, then I think there should be an entry about the offline usage of Spark NLP as there are probably many users working in offline scenarios but not having much of an idea on the recommended way for using this library. The entry should be prominent enough to be found through Search Engine queries and in Tutorials since this hurrdle is often one of the first when it comes to using the library in a closed environment.

**Comment by maziyarpanahi** [comment]
Hi @Dirkster99 

This is such a great discussion, thank you for creating it. As you mentioned, Spark NLP for Healthcare is being used by many companies in Healthcare and due to HIPAA rules, the majority of them are entirely air-gapped and using Spark NLP totally offline. 

Obviously, if you are behind a proxy or firewall without access to either:
- Maven repo, there is no other way rather than using the Fat JARs we provide on our S3 (links are in each release notes). You can also make your own via `sbt assembly` after cloning the repo. (I can see that you are doing that correctly)
- or access to S3, you cannot use `pretrained()` in annotators for downloading models or `PretrainedPipeline` for downloading pre-trained pipelines since they will be downloaded from S3. However, you can simple download any of them, extract them, and load them directly. (if you are local, this path can be local, if you are in the cluster, the path should be distributed FileSystem like HDFS, BDFS, S3, etc.)
https://nlp.johnsnowlabs.com/models

Now, on to the existing documentation. We do have online/offline for both Pipelines and Models here: 
- models used online and offline: https://github.com/JohnSnowLabs/spark-nlp#models
- pipelines used online and offline: https://nlp.johnsnowlabs.com/docs/en/pipelines#how-to-use

I can see that these two are in different places, so I will update the docs in the README under `models` and `pipelines` with better explanations and maybe more examples. Do you suggest other improvements or additional/extra info being added to the README and the docs on the Website? (since it's easy to do offline and we do support it 100%, it would be a shame users don't get to find it more easily)
