### ISSUE TITLE
Example for apply multiple pipelines or models in parallel?

### ISSUE THREAD

**Issue by rsuwaileh** [JohnSnowLabs/spark-nlp#2839]
Hey,

Are there any examples for running multiple pipelines/models in parallel? I actually need to run X NER models in parallel and combine their results. The preprocessing (tokenizing, normalizing, are shared among models). So, the only part I want to run in parallel is the fit-transform phases of the NER models.

Any pointers to achieve this goal?

**Comment by maziyarpanahi** [comment]
Hi,

In Spark jobs and tasks can be distributed but you cannot have two or more jobs/tasks running in parallel. It's always sequential in the pipeline. But I think what you meant from parallelism was a different definitions as how to reuse some annotators for multiple NER models.

You can have your own pipeline and have as many NER models as you wish considering you share the DocumentAssembler, SentenceDetectorDL, Tokenizer, and correct word embeddings models associated with that NER model. You pass the DataFrame and you'll get the results at the end, jobs and tasks will be distributed but they won't be parallel.

Please have a look at these training notebooks: https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/Certification_Trainings/Public especially `3.SparkNLP_Pretrained_Models.ipynb` notebook to see how to construct a pipeline.

All you need after is to find desired NER models from Models Hub: https://nlp.johnsnowlabs.com/models?task=Named+Entity+Recognition they all have code examples so you know which word embeddings model is required.

Here is a simple example, but you can extend this to more models. (just keep in mind the more different word embeddings you use the more resources you need since they are not shared. If you can find multiple NER models that use the same word embeddings model would be more efficient if possible)

```python
documentAssembler = DocumentAssembler() \
    .setInputCol('text') \
    .setOutputCol('document')

tokenizer = Tokenizer() \
    .setInputCols(['document']) \
    .setOutputCol('token')

embeddings_glove_100 = WordEmbeddingsModel.pretrained('glove_100d') \
    .setInputCols(["document", 'token']) \
    .setOutputCol("embeddings_100d")

embeddings_glove_300 = WordEmbeddingsModel.pretrained('glove_840B_300', 'xx') \
    .setInputCols(["document", 'token']) \
    .setOutputCol("embeddings_300d")

onto_100_model = NerDLModel.pretrained('onto_100', 'en') \
    .setInputCols(['document', 'token', 'embeddings_100d']) \
    .setOutputCol('ner_onto_100')

onto_300_model = NerDLModel.pretrained('onto_300', 'en') \
    .setInputCols(['document', 'token', 'embeddings_300d']) \
    .setOutputCol('ner_onto_300')

nlp_pipeline = Pipeline(stages=[
    documentAssembler, 
    tokenizer,
    embeddings_glove_100,
   embeddings_glove_300,
    onto_100_model,
    onto_300_model
])



+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|                text|            document|               token|     embeddings_100d|     embeddings_300d|        ner_onto_100|        ner_onto_300|
+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|William Henry Gat...|[[document, 0, 15...|[[token, 0, 6, Wi...|[[word_embeddings...|[[word_embeddings...|[[named_entity, 0...|[[named_entity, 0...|
|The Mona Lisa is ...|[[document, 0, 98...|[[token, 0, 2, Th...|[[word_embeddings...|[[word_embeddings...|[[named_entity, 0...|[[named_entity, 0...|
+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
```
