### ISSUE TITLE
Sentiment Analysis always positive

### ISSUE THREAD

**Issue by Tomczik76** [JohnSnowLabs/spark-nlp#38]
I'm evaluating this product and sentiment with the SentimentDetector always returns "result->positive". Does the package come with a trained model or do I have to train one myself?

```
    val spark = SparkSession
      .builder()
      .appName("Sentiment")
      .getOrCreate()

    import spark.implicits._

    val data = Seq(Article("I hate this natural language processor. It doesn't work at all!")).toDS

    data.cache()

    val documentAssembler = new DocumentAssembler().setInputCol("body")

    val sentenceDetector = new SentenceDetectorModel()
      .setInputCols(Array("document"))
      .setOutputCol("sentence")

    val regexTokenizer = new RegexTokenizer()
      .setInputCols("sentence")
      .setOutputCol("token")

    val sentimentDetector = new SentimentDetectorModel()
      .setInputCols(Array("sentence", "token"))
      .setOutputCol("sentiment")


    val finisher = new Finisher().setInputCols(Array("sentiment"))
      .setIncludeKeys(true)
      .setCleanAnnotations(false)


    val pipeline = new Pipeline().setStages(Array(
      documentAssembler,
      sentenceDetector,
      regexTokenizer,
      sentimentDetector,
      finisher
    ))

    val sentimentData = pipeline.fit(data).transform(data)
    sentimentData.show(false)
```
Results:
|I hate this natural language processor. It it doesn't work at all!|[[document,0,65,I hate this natural language processor. It it doesn't work at all!,Map()]]|[[document,0,38,I hate this natural language processor.,Map()], [document,39,64,It it doesn't work at all!,Map()]]|[[token,0,0,I,Map(sentence -> 1)], [token,2,5,hate,Map(sentence -> 1)], [token,7,10,this,Map(sentence -> 1)], [token,12,18,natural,Map(sentence -> 1)], [token,20,27,language,Map(sentence -> 1)], [token,29,38,processor.,Map(sentence -> 1)], [token,39,40,It,Map(sentence -> 2)], [token,42,43,it,Map(sentence -> 2)], [token,45,51,doesn't,Map(sentence -> 2)], [token,53,56,work,Map(sentence -> 2)], [token,58,59,at,Map(sentence -> 2)], [token,61,64,all!,Map(sentence -> 2)]]|[[sentiment,0,0,positive,Map()]]|result->positive  |

**Comment by saifjsl** [comment]
Hello @Tomczik76 

Yes, there are currently two sentiment analysis annotators, SentimentDetectorModel and ViveknSentimentApproach.

Both require training and for now there are no pre-trained annotators, the one you are using needs a setting **setDictPath()** which leads to a file that looks lke this:
> superb,positive
> bad,negative
> lack of,revert
> very,increment
> barely,decrement

ViveknSentimentApproach uses **setPositiveSourcePath** and **setNegativeSourcePath** to point to a folder with positive and negative sentiment text files, and trains from there. 

You can take a look at the tests for simple examples.

To improve:
1. Documentation to be more clear on this
2. Review not providing training data, should fail instead of returning positive

**Comment by saifjsl** [comment]
lack of further input. closed.
