### ISSUE TITLE
MLeap integration with spark-nlp

### ISSUE THREAD

**Issue by hollinwilkins** [JohnSnowLabs/spark-nlp#40]
MLeap provides a way to deploy Spark-trained pipelines to production-ready API servers

## Description
For NLP, the use cases for this abound. This library is great for training. Having an MLeap integration would mean we can deploy the models instantly to an API service.

Feel free to close this issue if you don't think it belongs here, I also made an issue in MLeap to track this integration: https://github.com/combust/mleap/issues/292

**Comment by saifjsl** [comment]
Thanks, we are currently evaluating this.

**Comment by hollinwilkins** [comment]
@saifjsl Sure thing. Let me know if you or anyone wants to jump on a Google hangout to discuss this more.

**Comment by thelabdude** [comment]
Just curious if any progress has been made on this one?

**Comment by anasamoudi** [comment]
Any updates here?

**Comment by maziyarpanahi** [comment]
Has anyone actually tried this to see if it works?  I am not familiar with MLeap so unless I see an error and how to reproduce it I can’t say for sure whether or not there should be an integration as we are natively built on top of Spark ML.

**Comment by alexander-n-thomas** [comment]
MLeap is library that has a serialization format and an execution engine. It is attempting to solve the common problem of "I built my model with batch framework, now I need a low latency evaluation framework". It does this by having parallel implementations of models and transformers (not estimators). In order to have sparknlp in mleap we would need to implementations sparknlp models/transformers in mleaps interface, as well as serializers. As an example, checkout their implementation of a CountVectorizerModel: https://github.com/combust/mleap/blob/master/mleap-core/src/main/scala/ml/combust/mleap/core/feature/CountVectorizerModel.scala. 

What's cool, is that they support Spark, scikit-learn, xgboost and tensorflow.

**Comment by maziyarpanahi** [comment]
Thanks @alexander-n-thomas, now I understand better as how MLeap does the serialization. I thought it was using Spark transformers in ML module so we could be compatible. It needs function by function or in our case annotator by annotator definition of how to do these serializations. 
I will take a loom at some existing examples and see how many of our annotators will be possible right away without any changes. If I can make one full pipeline transition with NerDLModel included that would be great!

**Comment by maziyarpanahi** [comment]
@alexander-n-thomas One last question, we should make these implementations and contribute them to MLeap or should we have them on our side and invoke them by some function?

**Comment by ianwdunlop** [comment]
We've started investigating both the spark-nlp models and whether we can use mleap to deploy them. If the necessary mleap transformers existed for spark-nlp then anyone could convert the models from spark-nlp into mleap format. See https://github.com/combust/mleap-docs/blob/master/mleap-runtime/custom-transformer.md for some examples. However, I think it would need some changes to the spark-nlp model source code but not too major.

**Comment by periperi24** [comment]
Any updates here?

**Comment by nviraj** [comment]
Hi, 
Would love to see this!

If it helps, the use case we have in mind is to create a Shiny dashboard which would load up a Spark-NLP artifact for predictions instead of using a spark connection every time we need to generate a prediction. 

Thanks in advance!.

**Comment by maziyarpanahi** [comment]
In order to make MLeap work out of the box, we need to register those custom transformers inside MLeap. (like they have for most Spark ML functions - not all!). I am not sure this is something that can be done since they have only done this for some ML/DL libraries. (if they open up external contributions to third-party custom transformers we can spend time to see what we can do, until then unfortunately it has to be done outside Spark NLP by the users)

In the meantime, 
- we have a very nice way of working with MLFlow for logging metrics, models, etc: https://medium.com/spark-nlp/spark-nlp-and-mlflow-for-serialization-and-experiment-tracking-c4549827ece4
- we also have a nice integration with Comet.ml (they have a free plan too): https://www.comet.ml/site/new-integration-comet-spark-nlp/
