### ISSUE TITLE
Can I define my own annotators in Spark-NLP

### ISSUE THREAD

**Issue by mengban** [JohnSnowLabs/spark-nlp#5685]
**Is your feature request related to a problem? Please describe.**
I have some dataset(lang: zh) that segmented by jieba already , and I don't want to use the bundled word segment model in Spark-NLP, but the data I loaded without **Annotation**   and cant't be used in Spark-NLP workflow.
So  I am wondering if there is a way that I can define custom annotator and  object like ** annotatorType** can be  automatically generated by custom annotators after a transform process.

**Describe alternatives you've considered**
Can Spark-NLP support [jieba](https://github.com/fxsjy/jieba) to segment word for chinese text?

**Comment by maziyarpanahi** [comment]
Hi @mengban 

If your Chinese dataset is already segmented, does this mean all the valid words are separated by whitespace or other delimiters?

Because if that's the case you don't have to use WordSegmenter, you can just simply use RegexTokenizer by setting the regex for splitting (either whitespace or any other delimiter that library is outputting for words) and the results will be annotatorType.TOKEN.

**Comment by mengban** [comment]
> Hi @mengban
> 
> If your Chinese dataset is already segmented, does this mean all the valid words are separated by whitespace or other delimiters?
> 
> Because if that's the case you don't have to use WordSegmenter, you can just simply use RegexTokenizer by setting the regex for splitting (either whitespace or any other delimiter that library is outputting for words) and the results will be annotatorType.TOKEN.
> https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/annotation/english/regex-tokenizer/regex_tokenizer_examples.ipynb

Sound like a GOOD idea  :D
