### ISSUE TITLE
Details on CONLL and NerDLApproach are missing in the Documentation

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#5698]
**Link to doc page in question (if any):**
https://nlp.johnsnowlabs.com/docs/en/annotators#ner-dl-named-entity-recognition-deep-learning-annotator
https://nlp.johnsnowlabs.com/docs/en/training#conll-dataset

**Name of the Spark NLP feature whose docs need improvement:**

NerDLApproach
CONLL

**What you think the docs should say:**
I am using the `NerDLApproach()` in [this notebook](https://github.com/Dirkster99/PyNotes/blob/master/PySpark_SparkNLP/NER/NER_with_BERT_Test_Local_TST_CONLL.ipynb) to train for NER task. For a hello world intent I've replaced:
- B-ORG with B-TST
- I-ORG with I-TST

in the CONLLs files [eng_TST.testa](https://github.com/Dirkster99/PyNotes/blob/master/PySpark_SparkNLP/NER/CONLLs/eng_TST.testa) and [eng_TST.train](https://github.com/Dirkster99/PyNotes/blob/master/PySpark_SparkNLP/NER/CONLLs/eng_TST.train) and saw that this works as it did for ORG before.

Cool :-) this really appears to be simple enough, great. But when I look into the documentation there seems to be some thinks simply missing

For starters I am missing a clear and precise reference on what the CONLL should contain. [Here is an example](https://huggingface.co/datasets/conll2003) of what I mean by that.

Now I know the **CONLL 2003** format from using an Internet search but I am still not sure about the restictions that are applicable when training the NerDLApproach with a custom dataset (please let me know if I a missing a page). I am, for example, not sure whether any of the 3 tags:

- part-of-speech (POS) tag
- chunk tag
- named entity tag

should have a certain syntax (eg: POS tag can never have more than three letters)? I am also wondering if the number of tags that can be trained with this model is somehow limited (eg.: a maximum of 64 different chunk tags can be trained with one model)?

Please enlighten me on these details.

Thanks for providing such a great framework :-)

**Comment by hatrungduc** [comment]
Hi @Dirkster99,

Thanks a lot for bringing this to our attention! I have updated the documentation for CoNLL but I think additional information like this should be included in the Documentation update.

As for your questions, as far as I'm aware, the word masking and regular expression might not be supported.

@maziyarpanahi What is your opinion on this?

**Comment by maziyarpanahi** [comment]
Hi,

- The CoNLL 2003 is a universal format as mentioned here correctly: https://www.clips.uantwerpen.be/conll2003/ner/
- Anything that is not in that format must be converted by the user
- Alternative formats of the word are not supported. Due to transfer learning in word embeddings and other tasks like stemming and lemmatization in Spark NLP, don't believe it's useful. That's being said, it's not something we can support due to our NER architecture
- There is an example of what this file should look like, which columns will be used, etc. : https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/4.NERDL_Training.ipynb
- The POS column is not used in NerDL as the examples/docs/tests portrait this
- There is no limit in the number of tags, characters, and embeddings dimensions. However, we have a limited number of default graph that supports most use cases, if you see an error with your corpus during the training, then you can refer to this notebook to create a new graph and point to it (if the training failed due to a number of classes etc.): https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/4.1_NerDL_Graph.ipynb (I suggest using your local environment, Colab changes all the time and its support for TF v1.x is going to through the same change)

**Comment by Dirkster99** [comment]
Hi @maziyarpanahi, thank you for your nice summary. I think I even get the limitation about the default grph now and might even be able to use the linked notebook successfully :-)

But should such information not be available in a Documentation page rather than an issue ticket?

**Comment by maziyarpanahi** [comment]
you are welcome @Dirkster99 

@hatrungduc Please add anything that might be missing from this conversation to the docs

In the meantime, we have this page: https://nlp.johnsnowlabs.com/docs/en/training#tensorflow-graphs and those notebooks for getting started with Spark NLP. We can extend this section for training NerDLApproach @hatrungduc
