### ISSUE TITLE
Performance of BertEmbeddings model

### ISSUE THREAD

**Issue by tovbinm** [JohnSnowLabs/spark-nlp#570]
I wonder how good is the runtime performance of BertEmbeddings model?

## Description
Since BertEmbeddings applies the underlying TensorFlow model on per row basis (and not in row batches) I would suspect the performance to be not great. 

The chain of calls is: BertEmbeddings -> AnnotatorModel.transform -> AnnotatorModel.dfAnnotate -> BertEmbeddings.annotate. The BertEmbeddings.annotate function runs batches on input columns, but still on a single row.

## Expected Behavior
I would like to know if there were any benchmarks performed with BertEmbeddings model and what were the results. 

## Possible Solution
Apply model in batches using `dataset.mapPartitions(it => it.grouped.map(group => ...))`

## Steps to Reproduce
N/A

## Context
N/A

## Your Environment
N/A

**Comment by maziyarpanahi** [comment]
Are you sure the batchSize is for input columns? This doesn't make any sense to batch the columns instead of documents/sentences/tokens.
```
val batchSize = new IntParam(this, "batchSize", "Batch size. Large values allows faster processing but requires more memory.")
```
I haven't done any benchmark, but the `BertEmbeddings` has batchSize:
https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala

And also when you create the model:
https://github.com/JohnSnowLabs/spark-nlp/blob/master/python/tensorflow/bert/create_bert.ipynb

In fact, every TF related annotator has batchSize in both creating the graph and as a param. I know by the fact in `NerDLModel` the batchSize is the number of sentences to be trained or predicted (depending on the operation). 

I will look into it, but what kind of benchmark do you have in mind? Does a simple transformation of document->sentence->token->bert embeddings would be enough?

**Comment by tovbinm** [comment]
As far as I understand, `TensorflowBert.calculateEmbeddings` is invoked by `BertEmbeddings` [here](https://github.com/JohnSnowLabs/spark-nlp/blob/e14c7fcfd9346d7b3f1b9b938f2535e9f4cbdc61/src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala#L100), but it operated on different input columns on the same row and not on multiple rows of the dataset.

**Comment by tovbinm** [comment]
I think a good benchmark would be a loading some text rich (longer that tweets ;) ) dataset with not trivial amount of rows (1-10 million), then applying sentence->token->bert embedding or even sentence -> bert embedding. and measure cpu & memory utilization across cluster.

**Comment by maziyarpanahi** [comment]
@tovbinm That's what we usually do for testing annotators in a cluster over a few million documents (obviously larger than Tweets, we don't have any tweets anyway).
However, let's say it takes 3 minutes with 40% CPU. This doesn't really help me to understand whether it's done in batch or row by row. We need two different situations to compare and see which one has less overhead and faster at the same time.

We are however evaluating our BERT Embeddings and the performance has been already mentioned for detail tests. I'll keep this thread updated with our findings.

**Comment by maziyarpanahi** [comment]
I can confirm now that the batchSize (only set when BERT model is created) is only used to check how many sentences being feed into TF graph. Assuming the input is `document` and it has more than 1 sentence. 
As you mentioned it may or may not improve the performance. For instance, if the inputCols is `sentence`, it goes sentence by sentence and bypasses this batchSize. However, each spark's executor gets a subset of rows and will work but all executors will work in parallel. One can increase the number of partitions on the DatFrame to achieve higher parallelism

I am currently assigned to fix the BertEmbeddings as it didn't take into account the user's custom Tokenizer for tokens alignment during NER training:
https://github.com/JohnSnowLabs/spark-nlp/pull/585

We will be having pre-release and BERT performance is one of the tasks in the upcoming release.

**Comment by tovbinm** [comment]
Thanks for looking into this. I will keep an eye for upcoming releases then.

**Comment by maziyarpanahi** [comment]
I have more info on this. When we create Bert model in our notebook we must set `maxSentenceLength`, `batchSize`, `caseSensitive`, and dimensions. In fact, these are only set from Python during creating Bert model before loading them inside Spark NLP. So after that none of them are changeable and will be discarded.
The only thing we can change in Spark NLP is the pooling layer. Which I added a new feature `poolingLayer` and it can be set to `0` as the first layer and fastest, `-1` as the last layer and `-2` as the `second-to-last-hidden layer`.

I mentioned the batchSize and how it could help to improve performance when you have a document with more than 1 sentence. However, in the worst-case scenario when each document has 1 sentence:

On a local server with 50 cores and 180G memory:
• 14k sentences take more than 16000 seconds on CPU (27 minutes)
• 14K sentences take around 500 seconds on Tesla P100 GPU (less than 10)
•  17K sentences take around 120 seconds on a CPU-based Spark cluster with 10 executors each 5 cores!
This has been tested on a Bert Model with 256 max sentence length and `second-to-last-hidden layer` which is way slower due to encoding from sentence's context.

Two things are very important, first is that Bert is GPU optimized not CPU. The second is, we distribute TensorFlow over Spark so this boost parallelism into prediction which as you can see it beats a single GPU. (now if you have GPU Spark cluster then this would be flying)

Hope these help! :)

**Comment by tovbinm** [comment]
Thanks a lot for testing this out! That’s very helpful and sets a proper baseline for our own tests.

**Comment by alwayscurious** [comment]
@maziyarpanahi can you share the code/notebook you used to perform this test? I would like to reproduce it on a spark cluster.

**Comment by maziyarpanahi** [comment]
@alwayscurious 
That was a long time ago. Since then, we improved BertEmbeddings a lot! The layers were removed so it only uses the last hidden layer now and we introduced all the Small BERT models which fly on the CPU. 

Simply use the `BertEmbeddings` with any of the BERT models (https://nlp.johnsnowlabs.com/models) and save it on disk. (I used CoNLL 2003 dataset that has 14k sentences and timed that)

PS: In Spark NLP 2.7.4, you can transform over 120K news datasets with `small_bert_L2_128` (Tiny BERT) model within 46 seconds on 10 nodes (each 8G memory - Databricks/AWS).

**Comment by alwayscurious** [comment]
@maziyarpanahi great to hear! Do I need to save the model to disk directly after instantiating or is it ok to save it as part of a pipeline? I typical have a pipeline like this:

`ner_pipeline = RecursivePipeline(stages=[
    DocumentAssembler().setInputCol("text").setOutputCol("document"),
    SentenceDetector().setInputCols(["document"]).setOutputCol("sentence"),
    Tokenizer().setInputCols(["sentence"]).setOutputCol("token").setMaxLength(100).setSplitChars(["-", "\xa0", "—"]),
    BertEmbeddings.pretrained(name = "bert_large_cased", lang='en').setInputCols(['sentence', 'token']).setOutputCol('embeddings'),
    NerDLModel.pretrained('onto_bert_large_cased', 'en').setInputCols(['sentence', 'token', 'embeddings']).setOutputCol('ner'),
    NerConverter().setInputCols(['sentence', 'token', 'ner']).setOutputCol('ner_chunk')
  ])`

That I save after fitting the pipeline over data. I'll measure the performance of this over CoNLL 2003 dataset and the larger news dataset.

**Comment by maziyarpanahi** [comment]
Here is an example of a benchmark I use in Scala: https://github.com/JohnSnowLabs/spark-nlp/blob/a116ea390bd026b994d7506aa2e4be436cf4a888/src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala#L94

Obviously, you can use whatever you use to measure time. If you are benchmarking BertEmbeddings, just load the data, transform it over BertEmbeddings and save it with timing. No need to save the model or include other annotators. But again, it's really up to you how you time something based on your needs and your dataset to get a baseline for scaling.

Best of luck.
