### ISSUE TITLE
Training Classifiers model with SentenceEmbeddings Performance issue after sparknlp v3.3.2 (BertEmbeddings doesn't respect previous sentence IDs)

### ISSUE THREAD

**Issue by Cabir40** [JohnSnowLabs/spark-nlp#6850]
## Description

We are trying to run the training classification model with bert embeddings section in [this notebook](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/5.Text_Classification_with_ClassifierDL.ipynb)

Although we tried all the embeddings below and played with the parameters, we couldn't improve the accuracy over 0.35 in these versions:

pyspark==3.2.0 spark-nlp==3.4.0
pyspark==3.1.2 spark-nlp==3.4.0
pyspark==3.1.2 spark-nlp==3.3.4
pyspark==3.1.2 spark-nlp==3.3.3 

But it performs well in pyspark: v3.1.2 , spark-nlp: v3.3.1 and sparknlp: v3.3.2 versions.

Platform: Google Colab

## Expected Behavior

![image](https://user-images.githubusercontent.com/64752006/152349593-94c787a6-b68b-450d-81a0-e39014bbff00.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/64752006/152344258-6cf64f0e-ad51-49e7-9cb8-e680332260f8.png)
![image](https://user-images.githubusercontent.com/64752006/152344289-c7603b1f-0f1b-4ead-a6b7-f157e216550c.png)
![image](https://user-images.githubusercontent.com/64752006/152344414-c8168572-d70c-4193-a6b0-919703734786.png)
![image](https://user-images.githubusercontent.com/64752006/152344122-fca97f8d-96a8-44bb-afca-308ab752ecdc.png)

## Possible Solution

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
It's really hard to give any recommendations without having any idea what the dataset is about. (how many classes, how balanced the classes are, what is the nature/domain of the context, etc.)

When the result is that bad, there is something wrong with the dataset or the way it is used in the pipeline. (the model itself is fine so no need to test across different releases).

I would do the following:

- Make sure always set the `.setMaxSentenceLength(512)` which is the maximum in all Transformer models (BERT, ALBERT, etc.). This way you make sure you get enough context from each document
- Depending on the dataset (needs cleaning, words/sentences don't make much sense without the whole paragraph, etc.), I would suggest switching up to pure Sentence Embeddings annotators instead of `Word Embeddings` + `SentenceEmbeddings`. I would try the following and remove the `BertEmbeddings` + `SentenceEmbeddings` to see what happens (but again, if your dataset is domain-specific these generic English embeddings might not be enough)


```python
embeddingsSentece = BertSentenceEmbeddings.pretrained("sent_bert_use_cmlm_en_base", "en") \
      .setInputCols("sentence") \
      .setOutputCol("sentence_embeddings")\
      .setMaxSentenceLength(512)

```

- also, you can try with higher Epochs and lower `Lr` like these 3 parameters in ClassifierDLApproach:
```
classsifierdl = ClassifierDLApproach()\
      .setInputCols(["sentence_embeddings"])\
      .setOutputCol("class")\
      .setLabelColumn("category")\
      .setMaxEpochs(20)\
      .setLr(0.0001)\
      .setBatchSize(8)\
      .setEnableOutputLogs(True)
```

**Comment by maziyarpanahi** [comment]
@Cabir40 I just saw you mentioned it worked good in earlier versions and not in the latest ones. So I debugged this further, it turns out at some point `SentenceEmbeddings` returns mostly empty embeddings hence the terrible accuracy!

@danilojsl this issue was introduced when we fixed another issue here: https://github.com/JohnSnowLabs/spark-nlp/blob/f0ae084abffddcc1bef6e7eab86755cade3cf000/src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala#L192 The problem is, not every annotator (embeddings) respect those indexing, so it works perfectly with WordEmbeddings. but most of the result is empty if we use BertEmbeddings: https://colab.research.google.com/drive/14nOFfKS4XunZh2Doa6x5_KpOEb6UbJpo?usp=sharing

**Comment by maziyarpanahi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SentenceEmbeddings return empty embeddings after last fix (concatenation in Python)](https://trello.com/c/FKfUKyCu/523-sentenceembeddings-return-empty-embeddings-after-last-fix-concatenation-in-python)

**Comment by maziyarpanahi** [comment]
This is actually a bug inside `BertEmbeddings` which overrides the sentence ids from 0 to batchSize. Will be fix in the next release

**Comment by maziyarpanahi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BertEmbeddings overrides sentenceIndex from 0 to batchSize](https://trello.com/c/FKfUKyCu/523-bertembeddings-overrides-sentenceindex-from-0-to-batchsize)
