### ISSUE TITLE
Modify Doc2VecApproach.scala

### ISSUE THREAD

**Issue by lival** [JohnSnowLabs/spark-nlp#6917]
Persist or cache API  is widely used  to improve performance for spark applications. The variable  _input_ at Doc2VecApproach.scala:289 is used many times. We should call persist to accelerate calculation. The fixed code is like [this pull request](https://github.com/JohnSnowLabs/spark-nlp/pull/6918):
` val input = dataset.select(dataset.col(inputColumns)).rdd.map(r => r.getSeq[String](0)).cache()` 

We run Doc2VecExample.scala from spark-nlp  and observe WebUI . We found that the computation of two jobs (job0 and job1) both depends on RDD6  which is created by the  variable  _input_ .  Fixing this problem can helps us improve the execution efficiency.  Similar to the problem mentioned by spark16880," the input data should be persist during the ANN layer training to avoid redundant calculation".

**Comment by maziyarpanahi** [comment]
Hi,

We cannot use .cache nor .persist inside the library. This is something that must happen on the user’s side with the knowledge they have from their environment. Whether the data can be fit into the memory or gets spilled on the disks can result in OOV or slowness of the ops if one uses .cache without monitoring Spark UI.
You can cache your DataFrame and enforce it via .cache.count before passing it to the pipeline, but after that we cannot do it inside the library, it’s really a user-level action.

**Comment by lival** [comment]
Our tool analyzes the DAG of the application during execution and finds that the variable _input_ at Doc2VecApproach.scala:289 is used many times. So we suggest _input_ should be cache.  It consider the application features when making cache decision. As you mentioned the environment , either user-level action or library-level action maybe suffer form the same problem. 
Used cache API in Spark applications, we can better use the memory since the Spark is  a in-memory computing-based framework. when the memory is sufficient, cache API is used would improve performance. When the memory is not enough, it may cause the OOM or slowness. To solve this problem, users usually increase the memory space to ensure the correctness of the function. Cache is used inside the library maybe can also help developers to improve efficiency.

Thanks your idea, "Param that setEnableCache and make it false by default".  It maybe also difficult for user to know enough memory, but the  memory changes continuously as the application execution.

**Comment by maziyarpanahi** [comment]
Thanks @lival 

I did another analysis, actually the line `289` that uses `dataset` is the exactly DataFrame coming from `.fit(your_dataframe)`. So if you cache your DataFrame before passing it to .fit/.transform will be the equivalent to the .cache inside the library. The only difference here is, if the memory is not sufficient it will lead to OOV or slowing the whole process since it has to cache a large amount of data into memory and then on disk, so the result can be an exception or a total overhaul. (slower than not having cache anywhere at all)

I still believe this should be on the user level, they really should know the partitioning, fine-tuning, scaling, and anything else Apache Spark recommends to use to improve the performance (while keeping an eye on the Spark UI) instead of a library enforcing it. (waiting for a long time just to see an OOV that suggests you have no other choice but having more memory especially for users on a laptop is not a choice we can force people into for instance)

I'll do another run to make sure the whole training (including time spent to cache) is beneficial if we do it internally via that Param (will be definitely false by default so we don't force anyone). I'll do this on small and large on both local and cluster setups (sometimes caching in a cluster becomes even slower due to possible shuffling). I'll update this thread with my findings and the possibility of having that param

**Comment by maziyarpanahi** [comment]
> Maybe we also can try this ( The _cache_ API can be added by default, and the user has the option to set able by parameter ).

Yes, this would be the best option. Not trapping users on something that they have no way out of but moving to a bigger machine(s). I will do some tests this weekend and come back to you. (but it's safe to say we can include setEnableCache param to most of our trainable annotators since users can turn it on/off by monitoring the whole process)
