### ISSUE TITLE
from sparknlp.annotation import Annotation

### ISSUE THREAD

**Issue by padouk** [JohnSnowLabs/spark-nlp#703]
The newly added class: sparknlp.annotation.Annotation cannot be used in python
The following code will fail
```python
from sparknlp.annotation import Annotation
from sparknlp.functions import map_annotations_strict

def a(b):
  pass
map_annotations_strict(a)
map_annotations_strict(a)
```

ImportError: cannot import name 'Annotation' from 'sparknlp' (/local_disk0/spark-e01a4984-8cf3-4d61-a856-25bc16f07848/userFiles-e9441d9d-8881-4494-9b32-0a8cee49c3ff/addedFile3672637387921904645spark_nlp_2_3_4-acec0.jar/sparknlp/__init__.py)

You can easily narrow it down to this imposed sequence of execution
```
from sparknlp.annotation import Annotation
sys.modules['sparknlp.annotation'] = sparknlp  # Makes Annotation() pickle serializable in top-level
from sparknlp.annotation import Annotation
```

## Your Environment
* Version
SparkNLP: 2.3.4
Python 3.7
* Operating System 
Databricks Community Cluster: 6.1 (includes Apache Spark 2.4.4, Scala 2.11)

**Comment by saif-ellafi** [comment]
Thanks for reporting this, this seems to work if you import full module though:

`from sparknlp.annotator import *`

**Comment by saif-ellafi** [comment]
I am finding this issue "difficult" to fix.

I alleviate your particular code case here: https://github.com/JohnSnowLabs/spark-nlp/pull/719

However, this problem will still happen if you try to import `Annotation` after you have used either `map_annotations` or `map_annotations_strict` because of an internal hack I am doing inside those functions to move `Annotation` to top level so Pickle can serialize it.

I am trying other solutions but non of them seem to work.
