### ISSUE TITLE
Different cluster confs didn't change the training time when training NerCRF model.

### ISSUE THREAD

**Issue by jackieair** [JohnSnowLabs/spark-nlp#7684]
## Description

Actually, it's not a bug because the training process is successful, but I'm puzzled by what happened to me.

I follow https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/blogposts/data_prep.ipynb to train NerCRF in **spark** (not pyspark), and I tried different confs like:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Z00601~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Z00601~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

id | maxEpoch | num_executors | num_cores | executor_memory | num_partition | train_time
-- | -- | -- | -- | -- | -- | --
1 | 15 | 59 | 4 | 15 | 236 | 641.64
2 | 15 | 5 | 2 | 20 | 10 | 612.063
3 | 15 | 1 | 1 | 25 | 1 | 636.921
4 | 15 | 2 | 2 | 30 | 4 | 657.285

</body>

</html>

As you can see the training time are **quite close**, I don't see why this happens. Could you please help to find the cause?

## Expected Behavior

The training time with the best conf (id1) should have the best performance and minimum training time.
## Current Behavior

The training time for 4 confs are quite similar, no performance difference observed.
## Steps to Reproduce

1. follow https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/blogposts/data_prep.ipynb
2. change the training steps from Pyspark style to Spark Scala style.
3. Loading train dataset and WordEmbeddingsModel, set NerCrfApproach()
4. Use pipeline to fit the train dataset

## Your Environment

* Spark NLP version `sparknlp.version()`:Fat JARs
* Apache NLP version `spark.version`:3.1.2
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:linux
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi @jackieair 

All the training of models (trainable annotators) happens inside the Driver, increasing the number of executors won't change that. (we don't have distributed trainings, only Word2Vec and Doc2Vec can be distributed over the cluster)

**Comment by jackieair** [comment]
> Hi @jackieair
> 
> All the training of models (trainable annotators) happens inside the Driver, increasing the number of executors won't change that. (we don't have distributed trainings, only Word2Vec and Doc2Vec can be distributed over the cluster)

Thank you for your response!  

May I ask why you don't implement distributed training for LinearChainCrf? 
Is it hard to achieve or there's no need to do that, just curious about that.

If possible, I'd like to be a contributor to make that happen.

**Comment by maziyarpanahi** [comment]
Distributed training is very complicated and if the dataset can be fit into the memory (including the model itself) a single machine always beats distributed system in terms of speed. The `tf.distribute.Strategy` is not available in Java (yet) so for TensorFlow trainable annotators there is only a single machine, but even with a small GPU they are very fast already. 

If you find a pure ML annotator like NerCRFAppraoch you are welcome to contribute. In fact, any and all contributions are more than welcome here! 🙏  (as an example you can look into a work we've done inside `PerceptronApproachDistributed`, unfortunately, the data for Part of Speech are not large enough to be worth distributing that model and this annotator ends up being slower due to distribution overhead and that's why we don't advertise it - but something heavy that requires lots of data and iterations might benefit from distribution)
