### ISSUE TITLE
Different Outputs for Pyspark and Scala on same input data

### ISSUE THREAD

**Issue by saicharannivarthi** [JohnSnowLabs/spark-nlp#815]
## Description
I've tried the BERT Embeddings & ner_dl_bert model in PySpark and then tried the same in Scala. Ideally, there shouldn't be any difference in the output. But there is.

## Expected Behavior
Same output for Pyspark and Scala

## Current Behavior
Different output for Pyspark and Scala

## Steps to Reproduce

1. Input Data : https://github.com/saicharannivarthi/spark_nlp_issue_resources/blob/master/input_data.json
2. code in PySpark(done in Google Colab): https://github.com/saicharannivarthi/spark_nlp_issue_resources/blob/master/SparkNLP_Issue_Replication.ipynb
3. output from Pyspark: https://github.com/saicharannivarthi/spark_nlp_issue_resources/blob/master/pyspark_output.json

4. code in scala : https://github.com/saicharannivarthi/spark_nlp_issue_resources/blob/master/bert_scala.scala

5. output from scala
https://github.com/saicharannivarthi/spark_nlp_issue_resources/blob/master/scala_output.json

## Context

When I am experimenting as POC in PySpark, and when I shift to productionizing the pipeline in Scala, the outputs are not the same. 
## Your Environment

* Spark NLP version: 2.4.1 ( Scala ) 2.4.2 ( Pyspark )
* Scala version: 2.11.8
* Setup and installation for Pyspark: Google Colab
* Setup and installation for Scala: Local ( IntelliJ )
* Link to your project (if any):  All relevant files are available @ https://github.com/saicharannivarthi/spark_nlp_issue_resources

**Comment by maziyarpanahi** [comment]
All the annotators are using document as main input except the Tokenizer in Python which is using the sentence. Could you please fix that and try again, it should be document instead like the Scala.

**Comment by saicharannivarthi** [comment]
nice catch! I totally missed it. That solved the issue.
However, I wanna know how NER's performance differs if the input is a `sentence` or `document`?
Thanks for your time.

**Comment by maziyarpanahi** [comment]
The document is the whole row as the sentence will split into sentences, use embeddings on a sentence instead of the whole document and feed it for training and prediction to NerDL. It differs from dataset to dataset. If they are tweets, they are short so no need to split to sentences. If they are scientific abstracts, it is worth breaking them into sentences before. (Bert as a maxSentenceLength, so long document will be trimmed to the max length and the longer this value is the slower it gets. The best is between 128 to 512 characters)
You should evaluate it by doing some tests, however, using the sentence for large documents is advised.
