### ISSUE TITLE
load NerDLModel pipeline fail due to glove model missing

### ISSUE THREAD

**Issue by MadMenHitBooker** [JohnSnowLabs/spark-nlp#820]
The french model provided for using NerDLModel  doesn't work as it need a word embeddings input
## Description
When i try to load the french model
```scala
val ner = NerDLModel.load("/path/to/wikiner_840B_300_fr_2.4.0_2.4_1579699913554/").
      setInputCols("document","normal").
      setOutputCol("ner")
```

## Expected Behavior
It should load without error

## Current Behavior
I get an error which states:
```scala
Which should be columns from the following annotators: document, token, word_embeddings
```
When i try to use a word embedding i get the error:
```scala
Found input column with storage metadata. But such ref does not match to the ref this annotator requires. Make sure you are loading the annotator with ref: glove_840B_300
```

## Possible Solution
I think that the model need the glove embedding used for the french model. But i can't find it on the website

## Steps to Reproduce
Create a pipeline with NerDLModel and use the french model

## Context
i wanted to extract entities from documents

## Your Environment

* Spark NLP version: 2.4.4
* Apache NLP version:2.4.4
* Setup and installation (Pypi, Conda, Maven, etc.): pip
* Operating System and version: redhat 7 
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

We have 2 concepts in Spark NLP (or even Apache Spark): models and pipelines.

**Model**: Is an individual model related to an annotator. You can train an annotator, in this case, NerDLApproach and the result is NerDLModel which can be saved and used later on inside of a `pipeline` alongside other `annotators`.

**Pipeline**: This is a combination of models next to each other which servers one purpose and it can also be saved and used as a one-stop place to do bunch tasks without loading anything extra.

**When to use pre-trained pipelines:**
When the end to end offered task(s) inside that pipeline is suitable for your own NLP task. You don't require control and flexibility as the pipeline does offer what you need.

**When to use pre-trained models:**
When you need to create custom pipelines where you have full control over used pre-trained models and their inputs/outputs.

**Example of a pre-trained pipeline:**

```scala
import com.johnsnowlabs.nlp.pretrained.PretrainedPipeline
import com.johnsnowlabs.nlp.SparkNLP

SparkNLP.version()

val testData = spark.createDataFrame(Seq(
(1, "Google has announced the release of a beta version of the popular TensorFlow machine learning library"),
(2, "Donald John Trump (born June 14, 1946) is the 45th and current president of the United States")
)).toDF("id", "text")

val pipeline = PretrainedPipeline("recognize_entities_dl", lang="en")

val annotation = pipeline.transform(testData)

annotation.show()

annotation.select("ner_converter.result").show(false)
```
As you can see by just loading `recognize_entities_dl` we were able to transform new data without loading any other models since they are all inside this pipeline.

**Example of a pre-trained model inside of a custom pipeline:**

```scala
//custom pipeline
   val documentAssembler = new DocumentAssembler()
      .setInputCol("text")
      .setOutputCol("document")

    val sentenceDetector = new SentenceDetector()
      .setInputCols("document")
      .setOutputCol("sentence")

    val tokenizer = new Tokenizer()
      .setInputCols("sentence")
      .setOutputCol("token")

  val glove = WordEmbeddingsModel.pretrained(name ="glove_100d", lang="en")
      .setInputCols("token", "sentence")
      .setOutputCol("embeddings")
      .setCaseSensitive(false)

    val ner = NerDLModel.pretrained(name ="ner_dl", lang = "en")
      .setInputCols("sentence", "token", "embeddings")
      .setOutputCol("ner")

val nerConverter = new NerConverter()
      .setInputCols("sentence", "token", "ner")
      .setOutputCol("entities")

    val pipeline = new Pipeline()
      .setStages(Array(
        documentAssembler,
        sentenceDetector,
        tokenizer,
        glove,
        ner,
        nerConverter
      ))


val testData = spark.createDataFrame(Seq(
(1, "Google has announced the release of a beta version of the popular TensorFlow machine learning library"),
(2, "Donald John Trump (born June 14, 1946) is the 45th and current president of the United States")
)).toDF("id", "text")

val PipelineDF = pipeline.fit(testData).transform(testData)

PipelineDF.show()

```
