### ISSUE TITLE
sparknlp offline - unresolved dependencies

### ISSUE THREAD

**Issue by sahilsingh1123** [JohnSnowLabs/spark-nlp#828]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version: 2.4.3
* Apache NLP version: apache spark 2.4.5
* Setup and installation (Pypi, Conda, Maven, etc.): pip
* Operating System and version: ubuntu
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
please complete the template and explain the way to reproduce the issue. Just a title is not enough.

**Comment by sahilsingh1123** [comment]
I have updated the info. please have a look

**Comment by maziyarpanahi** [comment]
It's not possible to use 'com.johnsnowlabs.nlp:spark-nlp_2.11:2.4.3' without internet! It requires the Internet. 

For offline usage, after you did `pip install spark-nlp` with the Internet (one time need only), you need to compile the library or use the JAR we provide with `jars` instead of packages.
The jar is usually provided in each release at the bottom of the page.

**Comment by sahilsingh1123** [comment]
is there any proper documentation from where I can take the reference for using it in offline mode.

**Comment by sahilsingh1123** [comment]
and can you please provide me your slack address so that I dont have to create the issue everytime i face an error. thankyou

**Comment by sahilsingh1123** [comment]
i got the jar,  thankyou. but do provide me your slack.

**Comment by maziyarpanahi** [comment]
The link is in the readme, website and every repo.

**Comment by sahilsingh1123** [comment]
ok thankyou
