### ISSUE TITLE
BertEmbeddings simply ignores custom dimensions

### ISSUE THREAD

**Issue by adornes** [JohnSnowLabs/spark-nlp#903]
Hi friends,

It took me a long time and many executions to realize that BertEmbeddings was simply ignoring the value that I was parametrizing to `setDimension()` . So, I looked at the code and found this line. If I understand it correctly, it would always ignore this `set` method and keep the default 768.
Thks!

https://github.com/JohnSnowLabs/spark-nlp/blob/c65cddc2a6268d2c0815fb79760f4a4ccdc017e9/src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala#L107

**Comment by maziyarpanahi** [comment]
Hi,
That param is just for the metadata, you cannot change the dimensions of the BERT model. It’s either 768 for base or 1024 for large. 
This is same as original BERT and we only use the dimensions so users can use getDimension() to get the dimensions we set during the save. (If it’s empty by default assumes 768, but in our models it’s never empty. It doesn’t change anything since we cannot change BERT dimensions anywhere else)
