### ISSUE TITLE
tests-jar in release

### ISSUE THREAD

**Issue by lorenz-nlp** [JohnSnowLabs/spark-nlp#98]
## Description

When implementing an own AnnotatorModel, I would love to (re)-use text-fixtures of Spark NLP, such as AnnotatorBuilder or DataBuilder

## Expected Behavior
spark-nlp-${spark-nlp-version}-tests.jar is provided in the spark repo, so that it can be used as a test-dependency

## Current Behavior
No spark-nlp-${spark-nlp-version}-tests.jar is provided

## Possible Solution
In maven, the jar-plugin would take care of that. However, I don't know the equivalent in SBT

## Steps to Reproduce
Maven dependency:

`<dependency>
        <groupId>JohnSnowLabs</groupId>
        <artifactId>spark-nlp</artifactId>
        <version>${spark-nlp-version}</version>
	<type>test-jar</type>
        <scope>test</scope>
</dependency>`

## Context
Writing unit-tests for own Annotators

## Your Environment
* Version used: 1.3.0

**Comment by showy** [comment]
@lorenz-nlp I really like this idea. We'll check to extract the tests utilities into their own artifact .

**Comment by lorenz-nlp** [comment]
@showy Great, I'm looking forward to it, many thanks!

**Comment by showy** [comment]
@lorenz-nlp For our new release 1.4.0 we published the test artifacts. Let me know if you have any problem.

**Comment by lorenz-nlp** [comment]
Many thanks for your quick reaction! I upgraded today to v1.4.0 in order to use the test artifacts. However, I was not able to retrieve them, and in Maven Central no test artifacts are known (https://dl.bintray.com/spark-packages/maven/JohnSnowLabs/spark-nlp/1.4.0/). Would you be so kind to check?

Best, Lorenz

**Comment by saifjsl** [comment]
I'm wondering whether the AnnotatorBuilder and the DataBuilder wouldn't be useful on the main repo actually...

**Comment by showy** [comment]
@lorenz-nlp actually the test artifact was built for the maven central repository. You can retrieve it from here https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spark-nlp_2.11%22 . Is there any specific reason why you are using the spark packages repo in order to retrieve it? In any case we'll try to also add it to our next releases.

@saifjsl I would prefer to leave them out the main build from now. But as you say if those helper are requested a lot we can move them, our create a spark-nlp-utils artifact with those helpers.

**Comment by lorenz-nlp** [comment]
@showy It seems like I accidentally used "JohnSnowLabs" as the groupId, and this has forced me to get the jars from the Spark packages repo. Once I switch the groupId to "com.johnsnowlabs.nlp", the test-jars will be provided by maven central apparently. Thanks a lot! 

Btw, is there a reason why the coordinates of the releases vary depending on the repo?

**Comment by showy** [comment]
@lorenz-nlp actually we deploy all versions to spark-packages and to maven central. We deploy to maven central for the dependencies in the development projects and  we  deploy to spark packages so that the library can be easily downloadable with the spark command ```--package JohnSnowLabs:spark-nlp:version``` . We know that the package command could also download from maven central directly but the coordinate would be different and is a little harder to remember. 

Given that you will be able to download the test artifacts I'm going to close this issue. Re-open it if you find a problem. Thanks for the input.
