### ISSUE TITLE
storageRef hardcoded for UniversalSentenceEncoder

### ISSUE THREAD

**Issue by malikhijazi** [JohnSnowLabs/spark-nlp#980]
Is there a reason storageRef is defaulted to "tfhub_use"? Setting this as a default makes this a hardcoded value and any call to `setStorageRef` results in the error `Exception in thread "main" java.lang.UnsupportedOperationException: Cannot override storage ref on UNIVERSAL_SENTENCE_ENCODER_4de71669b7ec. Please re-use current ref: tfhub_use`. Is there a workaround for this? Thanks in advance.

**Comment by maziyarpanahi** [comment]
You shouldn't be able to override the `storageRef` in our pre-trained embeddings models. The `storageRef` correlates with other pre-trained models trained by using those values. Each embedding has its own storageRef which is normally the name of the model itself: https://github.com/JohnSnowLabs/spark-nlp-models#embeddings

For instance, `classifierdl_use_trec6` was trained by using `tfhub_use` embeddings model which has the same `storageRef`. (being able to rename it means you will use the wrong embeddings, you won't get the desired results, and worst-case scenario it may crash because the model was expecting different dimensions). 

So, if you are using our pre-trained embeddings, the `storageRef` cannot be overridden which is for the safety of the other pre-trained models like NerDLModel, ClassifierDL, SentimentDL, etc. (some embeddings like WordEmbeddings can be trained, so in that case, you are allowed to set your own `storageRef`)

**Comment by malikhijazi** [comment]
Thanks for the clarification @maziyarpanahi !
