### ISSUE TITLE
Regex matcher possible bug

### ISSUE THREAD

**Issue by aytugkaya** [JohnSnowLabs/spark-nlp#988]
Hi,
When using "," inside curly braces such as "{,}"  while building rules for regex_matcher, I ran into a problem.

```
rules = '''
renal\s\w+, started with 'renal'
cardiac\s\w+, started with 'cardiac'
\b\w+ly\b, ending with 'ly'
\b[A-Z]\w+ly\b, staring with a capital letter ending with 'ly'
\S*\d+\S*, match any word that contains numbers
(\d+).?(\d{3,6})\s*(mg|ml|g), match medication metrics
'''

with open('ulyses_regex_rules.txt', 'w') as f:
    
    f.write(rules)
    
f.close()
```

......

```
regex_matcher = RegexMatcher()\
    .setInputCols('sentences')\
    .setStrategy("MATCH_ALL")\
    .setOutputCol("regex_matches")\
    .setExternalRules(path='./ulyses_regex_rules.txt', delimiter=',')
    

nlpPipeline = Pipeline(stages=[
# documentAssembler, 
 regex_matcher
 ])

empty_df = spark.createDataFrame([['']]).toDF("text")

pipelineModel = nlpPipeline.fit(empty_df)

match_df = pipelineModel.transform(ulyses_result)

```

When I execute the line: 

`match_df.select('regex_matches.result').show(50,truncate=100)`

I get a very long error message, which includes this:

Caused by: java.util.regex.PatternSyntaxException: Unclosed counted closure near index 12
(\d+).?(\d{3

I am using Ubuntu 20.04,
Spark Version 2.4.6
Spark NLP version 2.5.3
Java JDK 8
Conda installation

**Comment by maziyarpanahi** [comment]
Hi,

The issue is your delimiter. If you change your fille to:

```
(\d+).?(\d{3,6})\s*(mg|ml|g) # match medication metrics
```
And use this instead:
```python
    .setExternalRules(path='./ulyses_regex_rules.txt', delimiter='#')
```
Then it works. You chose a delimiter that is part of your rules `,`. 

![image](https://user-images.githubusercontent.com/5762953/89106727-a4fe4c00-d42c-11ea-8bbb-d6e8e9b758e6.png)


You can use anything for delimiter to make it unique and less possible to be included in your rules like `\t` etc.

Please let me know if this resolved your issue.

**Comment by aytugkaya** [comment]
Thanks, that worked for me.
