### ISSUE TITLE
[Help] Is it possible to perform transfer learning on pre-trained Embeddings?

### ISSUE THREAD

**Issue by JeroenSchmidt** [JohnSnowLabs/spark-nlp#989]
Hi I'm a new user of Spark-NLP and I was wondering if its possible to perform transfer learning on the pre-trained Embedding you have available for download. Also where in the documentation can I find examples of how the pre-trained embeddings are made?

**Comment by maziyarpanahi** [comment]
Hi,
The pre-trained models and pipelines are constant weights and cannot be fine-tuned. That's being said, you can use our many embeddings (word and sentence) during training for transfer learning.

All the embeddings come from the original models such as GloVe, BERT, ALBERT, XLnet, etc. 
https://github.com/JohnSnowLabs/spark-nlp-models#embeddings

**Comment by JeroenSchmidt** [comment]
Thanks @maziyarpanahi for your speedy reply. 
As a followup. Are the weights of the pre-trained embedding (GloVe, BERT, ALBERT, XLnet, etc.) fixed when I define a custom pipeline? or are they updated when the pipeline `fit()` function is called?

**Comment by maziyarpanahi** [comment]
You are welcome. None of the embeddings will change on fit(). You can train your own Word2Vec or glove or fine-tune BERT etc. Load them here but the pre-trained embeddings  not use the data to learn rather than transform. (Goove is syntactic word embeddings so a token has always the same vectors, however, the others are contextualized. Meaning depending on your sentence the vectors for each token changes)
